// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: base/proto/base/base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 普通 RPC 请求和响应
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_base_proto_base_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_base_proto_base_base_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_base_proto_base_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_base_proto_base_base_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 服务端流请求和响应
type StreamingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingRequest) Reset() {
	*x = StreamingRequest{}
	mi := &file_base_proto_base_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRequest) ProtoMessage() {}

func (x *StreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRequest.ProtoReflect.Descriptor instead.
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return file_base_proto_base_base_proto_rawDescGZIP(), []int{2}
}

func (x *StreamingRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingResponse) Reset() {
	*x = StreamingResponse{}
	mi := &file_base_proto_base_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingResponse) ProtoMessage() {}

func (x *StreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingResponse.ProtoReflect.Descriptor instead.
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return file_base_proto_base_base_proto_rawDescGZIP(), []int{3}
}

func (x *StreamingResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 双向流的消息
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stroke        string                 `protobuf:"bytes,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_base_proto_base_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_base_proto_base_base_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetStroke() string {
	if x != nil {
		return x.Stroke
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stroke        string                 `protobuf:"bytes,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_base_proto_base_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_base_proto_base_base_proto_rawDescGZIP(), []int{5}
}

func (x *Pong) GetStroke() string {
	if x != nil {
		return x.Stroke
	}
	return ""
}

var File_base_proto_base_base_proto protoreflect.FileDescriptor

const file_base_proto_base_base_proto_rawDesc = "" +
	"\n" +
	"\x1abase/proto/base/base.proto\x12\x04base\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"(\n" +
	"\x10StreamingRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\")\n" +
	"\x11StreamingResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x1e\n" +
	"\x04Ping\x12\x16\n" +
	"\x06stroke\x18\x01 \x01(\tR\x06stroke\"\x1e\n" +
	"\x04Pong\x12\x16\n" +
	"\x06stroke\x18\x01 \x01(\tR\x06stroke2\x92\x01\n" +
	"\x04Base\x12%\n" +
	"\x04Call\x12\r.base.Request\x1a\x0e.base.Response\x12;\n" +
	"\x06Stream\x12\x16.base.StreamingRequest\x1a\x17.base.StreamingResponse0\x01\x12&\n" +
	"\bPingPong\x12\n" +
	".base.Ping\x1a\n" +
	".base.Pong(\x010\x01B\x18Z\x16./base/proto/base;baseb\x06proto3"

var (
	file_base_proto_base_base_proto_rawDescOnce sync.Once
	file_base_proto_base_base_proto_rawDescData []byte
)

func file_base_proto_base_base_proto_rawDescGZIP() []byte {
	file_base_proto_base_base_proto_rawDescOnce.Do(func() {
		file_base_proto_base_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_proto_base_base_proto_rawDesc), len(file_base_proto_base_base_proto_rawDesc)))
	})
	return file_base_proto_base_base_proto_rawDescData
}

var file_base_proto_base_base_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_base_proto_base_base_proto_goTypes = []any{
	(*Request)(nil),           // 0: base.Request
	(*Response)(nil),          // 1: base.Response
	(*StreamingRequest)(nil),  // 2: base.StreamingRequest
	(*StreamingResponse)(nil), // 3: base.StreamingResponse
	(*Ping)(nil),              // 4: base.Ping
	(*Pong)(nil),              // 5: base.Pong
}
var file_base_proto_base_base_proto_depIdxs = []int32{
	0, // 0: base.Base.Call:input_type -> base.Request
	2, // 1: base.Base.Stream:input_type -> base.StreamingRequest
	4, // 2: base.Base.PingPong:input_type -> base.Ping
	1, // 3: base.Base.Call:output_type -> base.Response
	3, // 4: base.Base.Stream:output_type -> base.StreamingResponse
	5, // 5: base.Base.PingPong:output_type -> base.Pong
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_proto_base_base_proto_init() }
func file_base_proto_base_base_proto_init() {
	if File_base_proto_base_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_base_base_proto_rawDesc), len(file_base_proto_base_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_proto_base_base_proto_goTypes,
		DependencyIndexes: file_base_proto_base_base_proto_depIdxs,
		MessageInfos:      file_base_proto_base_base_proto_msgTypes,
	}.Build()
	File_base_proto_base_base_proto = out.File
	file_base_proto_base_base_proto_goTypes = nil
	file_base_proto_base_base_proto_depIdxs = nil
}
